### ISSUE TITLE
Automate toil tasks that can be automated.

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#216]
The outcome should be a list of tasks that are repetitive. We should start with low hanging tasks that are commonly enacted.

I'll aggregate suggestions in the list below: 

Edit: Updating this list below, the action item now is to complete this checklist.

Apps/repo:
- [ ] Adding new/existing cluster resources to cluster-scope app (in base), if it's new then a file is required. (https://github.com/operate-first/apps/issues/608)
    - e.g: `$./add_resource.sh clusterroles example-role moc zero` 
- [ ] Adding new/existing users to a group to an environment/cluster, this would require also encrypting this group (https://github.com/operate-first/SRE/issues/304)
    - e.g. `$./add_user "john,jane,bob" operate-first moc zero` 
- [ ] Create new ArgoCD project for an user group (covered in https://github.com/operate-first/SRE/issues/305)
- [ ] Add project admin/edit/view group for a namespace (https://github.com/operate-first/SRE/issues/278)
- [x] Enable monitoring on a namespace (this involves just adding the appropriate rbac) (https://github.com/operate-first/SRE/issues/277)
- [x] Script to bump openshift `ClusterVersion` resource based on available updates (https://github.com/operate-first/apps/pull/531)

Misc:
- [ ] Encrypting resources 
    - Currently some files require encrypting resources with 4 or more secrets, personally I find this a bit tedious, we opt not to use .sops.yaml due to reasons discussed [here](https://github.com/operate-first/SRE/issues/122), but maybe we can alleviate the pain of having to add multiple keys to the `--pgp` flag in some other way. (https://github.com/operate-first/SRE/issues/306)
- [ ] Auto-link docs for a given operator in issues for operator onboarding (https://github.com/operate-first/SRE/issues/307)
- [ ] Extracting the ca.crt secret for kafka onboarding from opf-kafka namespace (https://github.com/operate-first/SRE/issues/308)

Argocd-Apps:
- [ ] Create new ArgoCD app from a given repo and path for a specific namespace+cluster (https://github.com/operate-first/SRE/issues/305#issuecomment-840108267)

**Comment by 4n4nd** [comment]
Automate creation of PVC manifests from an issue:

User opens issue, bot parses request and creates a PR for the PVC manifest

**Comment by HumairAK** [comment]
@4n4nd how about we start with a simple script first, `$./script add odh/pvc moc zero jupyterhub-nb-johns-pvc -u john@doe.com -s 8Gi` -- then we can have the bot run these commands later.

**Comment by tumido** [comment]
- Create new ArgoCD app from a given repo and path for a specific namespace+cluster
- Create new ArgoCD project for an user group
- Add project admin/edit/view group for a namespace
- Enable monitoring on a namespace
- Auto-link docs for a given operator in issues for operator onboarding

**Comment by anishasthana** [comment]
How about something for updates to manifests when upstream has a new release? specifically thinking of ODH here

**Comment by HumairAK** [comment]
another task to automate: extracting the `ca.crt` secret for kafka onboarding from `opf-kafka` namespace

**Comment by 4n4nd** [comment]
After z stream updates, we should redeploy all our deployments instead of just JH.

**Comment by tumido** [comment]
Linking RH `cli` for git-ops https://github.com/redhat-developer/kam (disclaimer: it's very oppinionated)

**Comment by tumido** [comment]
- [ ] Script to bump openshift `ClusterVersion` resource based on available updates

**Comment by ipolonsk** [comment]
I will work on the " Enable monitoring on a namespace (this involves just adding the appropriate rbac)" task.

**Comment by ipolonsk** [comment]
I'm working on the "Add project admin/edit/view group for a namespace" task.

**Comment by HumairAK** [comment]
Let's convert all of these in to issues, and close this out.

**Comment by HumairAK** [comment]
All tasks were converted to separate issues, see epic backlog for further details. Closing for now. Re-open if anything was missed.
