### ISSUE TITLE
Prep prior to OpenShift Commons Gathering (25 Oct 2022 08:00 EDT)

### ISSUE THREAD

**Issue by quaid** [operate-first/sre#40]
Checklist of items to create or complete:

- [x] Update `README` to reflect shift to become SIG SRE -- #42 
- [x] Create `sig-roadmap.md` #38 
- [x] Landing page is https://operate-first.cloud/sig-sre or https://op1.st/sig-sre
  - [x] https://op1.st/sig-sre working
  - [x] https://www.operate-first.cloud/sre working (/sre because the repo is /sre, couldn't find quickfix to change)
  - [x] https://github.com/operate-first/sre/issues/39
- [ ] Create good-enough `charter.md` and mark it as provisional until the SIG can formally convene
- [ ] Name provisional initiating co-chairs by group consensus in CoreOS Slack today - **Provisional decision only** 
- [x] #41
- [ ] Create announce group `sig-sre-announce@groups.operate-first.cloud`
- [ ] Blog post explaining all this
- [x] QR code for presentation slide https://github.com/operate-first/sre/issues/45
- [ ] Short URL for presentation slide -- #45 
  - [x] link created, for now to repo /sre - [op1.st/sre-presentation](https://op1.st/sre-presentation)
  - [ ] changing link to real presentation slide

/assign @schwesig @quaid @lisa @jeremyeder

**Comment by schwesig** [comment]
@quaid - I created op1.st for shortening links.
what do you need for shorts?

**Comment by schwesig** [comment]
[op1.st/sre-presentation](https://op1.st/sre-presentation)
for now linking to the repo operate-first/sre, but this can be changed very fast (under 10 minutes)

svg:
![QR_https___op1 st_sre-presentation](https://user-images.githubusercontent.com/89909507/197653834-11151137-ccf2-498d-8b36-e73a29586a14.svg)

png:
![QR_https___op1 st_sre-presentation](https://user-images.githubusercontent.com/89909507/197653836-b0b18f12-77d8-4ad3-96ec-65f4e7df9d31.png)

**Comment by schwesig** [comment]
operate-first.cloud/sre/
is working

**Comment by schwesig** [comment]
qrcode for
https://op1.st/sig-sre

svg
![QR_https___op1 st_sig-sre](https://user-images.githubusercontent.com/89909507/197722683-d09727d2-883e-4bc2-8523-6182cf2f984d.svg)

png
![QR_https___op1 st_sig-sre](https://user-images.githubusercontent.com/89909507/197722690-8f920b65-1d93-4667-b8eb-7b4cd36ffa98.png)

**Comment by quaid** [comment]
Event completed successfully.

Note that not all tasks were completed (or needed for the event, in the end)
